create table if not exists public.lead_radar_leads (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text,
  title text not null,
  excerpt text not null default '',
  url text,
  published_at timestamptz not null,
  discovered_at timestamptz not null default now(),
  need_type text not null default '其他开发',
  is_lead boolean not null default true,
  intent_score integer not null default 0 check (intent_score between 0 and 100),
  fit_score integer not null default 0 check (fit_score between 0 and 100),
  freshness_score integer not null default 0 check (freshness_score between 0 and 100),
  ai_score integer not null default 0 check (ai_score between 0 and 100),
  urgency text not null default 'low' check (urgency in ('low','medium','high')),
  confidence integer not null default 0 check (confidence between 0 and 100),
  priority text not null default 'low' check (priority in ('low','medium','high')),
  budget_text text,
  reason text not null default '',
  signals jsonb not null default '[]'::jsonb,
  status text not null default 'new' check (status in ('new','saved','contacted','ignored')),
  dedupe_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lead_radar_leads_score_idx on public.lead_radar_leads (ai_score desc, published_at desc);
create index if not exists lead_radar_leads_status_idx on public.lead_radar_leads (status, published_at desc);
create index if not exists lead_radar_leads_discovered_idx on public.lead_radar_leads (discovered_at desc);

alter table public.lead_radar_leads enable row level security;
revoke all on table public.lead_radar_leads from anon, authenticated;
revoke all on sequence public.lead_radar_leads_id_seq from anon, authenticated;

create table if not exists public.lead_radar_scan_runs (
  id bigint generated by default as identity primary key,
  connector text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  scanned integer not null default 0,
  stored integer not null default 0,
  filtered integer not null default 0,
  high_intent integer not null default 0,
  status text not null default 'running' check (status in ('running','success','failed')),
  error_text text
);

create index if not exists lead_radar_scan_runs_started_idx on public.lead_radar_scan_runs (started_at desc);
alter table public.lead_radar_scan_runs enable row level security;
revoke all on table public.lead_radar_scan_runs from anon, authenticated;
revoke all on sequence public.lead_radar_scan_runs_id_seq from anon, authenticated;
