create table if not exists public.lead_radar_scan_requests (
  id bigint generated by default as identity primary key,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now(),
  status text not null default 'queued' check (status in ('queued','running','success','failed','cancelled')),
  requested_from text not null default 'web',
  query_override text,
  max_queries integer not null default 1 check (max_queries between 1 and 3),
  provider text not null default 'justone-xiaohongshu-v4',
  github_run_id text,
  result jsonb not null default '{}'::jsonb,
  error_text text
);

create unique index if not exists lead_radar_scan_requests_one_active_idx
  on public.lead_radar_scan_requests ((1))
  where status in ('queued','running');

create index if not exists lead_radar_scan_requests_requested_at_idx
  on public.lead_radar_scan_requests (requested_at desc);

alter table public.lead_radar_scan_requests enable row level security;
revoke all on table public.lead_radar_scan_requests from anon, authenticated;
revoke all on sequence public.lead_radar_scan_requests_id_seq from anon, authenticated;

create or replace function public.lead_radar_claim_scan_request(p_run_id text)
returns table (
  id bigint,
  query_override text,
  max_queries integer,
  requested_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidate as (
    select r.id
    from public.lead_radar_scan_requests r
    where r.status = 'queued'
    order by r.requested_at asc
    for update skip locked
    limit 1
  ), claimed as (
    update public.lead_radar_scan_requests r
    set status = 'running',
        started_at = now(),
        updated_at = now(),
        github_run_id = nullif(left(coalesce(p_run_id, ''), 120), '')
    from candidate c
    where r.id = c.id
    returning r.id, r.query_override, r.max_queries, r.requested_at
  )
  select c.id, c.query_override, c.max_queries, c.requested_at
  from claimed c;
end;
$$;

revoke all on function public.lead_radar_claim_scan_request(text) from public, anon, authenticated;
