create table if not exists public.lead_radar_intelligence_settings (
  id smallint primary key default 1 check (id = 1),
  semantic_enabled boolean not null default false,
  semantic_mode text not null default 'shadow' check (semantic_mode in ('off','shadow','enforce')),
  provider text not null default 'openai' check (provider in ('openai')),
  model text not null default 'gpt-5.4-nano',
  buyer_threshold integer not null default 72 check (buyer_threshold between 0 and 100),
  min_confidence integer not null default 65 check (min_confidence between 0 and 100),
  reject_confidence integer not null default 75 check (reject_confidence between 0 and 100),
  max_items_per_batch integer not null default 20 check (max_items_per_batch between 1 and 40),
  updated_at timestamptz not null default now()
);

insert into public.lead_radar_intelligence_settings (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.lead_radar_semantic_assessments (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text,
  content_hash text not null,
  intelligence_version text not null,
  policy_version text not null,
  provider text not null,
  model text not null,
  actor_role text not null check (actor_role in ('buyer','provider','recruiter','learner','content','unknown')),
  transaction_direction text not null check (transaction_direction in ('buy','sell','recruit','learn','discuss','unknown')),
  buyer_probability integer not null check (buyer_probability between 0 and 100),
  confidence integer not null check (confidence between 0 and 100),
  project_specificity integer not null check (project_specificity between 0 and 100),
  semantic_decision text not null check (semantic_decision in ('accept','reject','uncertain')),
  reason text,
  evidence jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (content_hash, intelligence_version, provider, model)
);

create index if not exists lead_radar_semantic_assessments_source_idx
  on public.lead_radar_semantic_assessments (source, source_id);
create index if not exists lead_radar_semantic_assessments_created_idx
  on public.lead_radar_semantic_assessments (created_at desc);
create index if not exists lead_radar_semantic_assessments_buyer_idx
  on public.lead_radar_semantic_assessments (buyer_probability desc, confidence desc);

alter table public.lead_radar_leads
  add column if not exists author_id text,
  add column if not exists author_name text,
  add column if not exists semantic_actor_role text,
  add column if not exists transaction_direction text,
  add column if not exists buyer_probability integer,
  add column if not exists semantic_confidence integer,
  add column if not exists project_specificity integer,
  add column if not exists intelligence_version text,
  add column if not exists semantic_model text;

alter table public.lead_radar_intelligence_settings enable row level security;
alter table public.lead_radar_semantic_assessments enable row level security;

revoke all on table public.lead_radar_intelligence_settings from anon, authenticated;
revoke all on table public.lead_radar_semantic_assessments from anon, authenticated;
revoke usage, select on sequence public.lead_radar_semantic_assessments_id_seq from anon, authenticated;

comment on table public.lead_radar_semantic_assessments is
  'Auditable semantic buyer-intent classifications. The model layer is a transaction-role classifier, not a keyword matcher.';
