alter table public.lead_radar_leads
  add column if not exists actor_role text not null default 'buyer',
  add column if not exists buying_stage text not null default 'none',
  add column if not exists actionability_score integer not null default 0,
  add column if not exists policy_version text not null default 'legacy';

do $$ begin
  alter table public.lead_radar_leads add constraint lead_radar_leads_actor_role_check
    check (actor_role in ('buyer','provider','recruiter','learner','content','unknown'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.lead_radar_leads add constraint lead_radar_leads_buying_stage_check
    check (buying_stage in ('explicit','paid','considering','problem','none'));
exception when duplicate_object then null; end $$;

do $$ begin
  alter table public.lead_radar_leads add constraint lead_radar_leads_actionability_score_check
    check (actionability_score between 0 and 100);
exception when duplicate_object then null; end $$;

create table if not exists public.lead_radar_query_metrics (
  query_key text primary key,
  query_text text not null,
  intent_family text not null,
  topic_family text not null,
  runs integer not null default 0,
  returned_count integer not null default 0,
  fresh_count integer not null default 0,
  qualified_count integer not null default 0,
  filtered_count integer not null default 0,
  duplicate_count integer not null default 0,
  last_run_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.lead_radar_query_metrics enable row level security;
revoke all on table public.lead_radar_query_metrics from anon, authenticated;

create or replace function public.lead_radar_record_query_metric(
  p_query_key text,
  p_query_text text,
  p_intent_family text,
  p_topic_family text,
  p_returned integer,
  p_fresh integer,
  p_qualified integer,
  p_filtered integer,
  p_duplicates integer
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.lead_radar_query_metrics (
    query_key, query_text, intent_family, topic_family,
    runs, returned_count, fresh_count, qualified_count, filtered_count, duplicate_count,
    last_run_at, updated_at
  ) values (
    left(coalesce(p_query_key, ''), 160), left(coalesce(p_query_text, ''), 240),
    left(coalesce(p_intent_family, ''), 80), left(coalesce(p_topic_family, ''), 80),
    1, greatest(coalesce(p_returned, 0), 0), greatest(coalesce(p_fresh, 0), 0),
    greatest(coalesce(p_qualified, 0), 0), greatest(coalesce(p_filtered, 0), 0),
    greatest(coalesce(p_duplicates, 0), 0), now(), now()
  )
  on conflict (query_key) do update set
    query_text = excluded.query_text,
    intent_family = excluded.intent_family,
    topic_family = excluded.topic_family,
    runs = public.lead_radar_query_metrics.runs + 1,
    returned_count = public.lead_radar_query_metrics.returned_count + excluded.returned_count,
    fresh_count = public.lead_radar_query_metrics.fresh_count + excluded.fresh_count,
    qualified_count = public.lead_radar_query_metrics.qualified_count + excluded.qualified_count,
    filtered_count = public.lead_radar_query_metrics.filtered_count + excluded.filtered_count,
    duplicate_count = public.lead_radar_query_metrics.duplicate_count + excluded.duplicate_count,
    last_run_at = now(),
    updated_at = now();
end;
$$;

revoke all on function public.lead_radar_record_query_metric(text,text,text,text,integer,integer,integer,integer,integer) from public, anon, authenticated;

create table if not exists public.lead_radar_feedback (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text not null,
  label text not null check (label in ('lead','maybe','not_lead')),
  reason_code text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, source_id)
);

create index if not exists lead_radar_feedback_label_idx on public.lead_radar_feedback (label, updated_at desc);
alter table public.lead_radar_feedback enable row level security;
revoke all on table public.lead_radar_feedback from anon, authenticated;
revoke all on sequence public.lead_radar_feedback_id_seq from anon, authenticated;
