create table if not exists public.lead_radar_seen_items (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text,
  dedupe_key text not null unique,
  disposition text not null default 'seen' check (disposition in ('seen','filtered','stored','duplicate','error')),
  lead_id bigint references public.lead_radar_leads(id) on delete set null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create unique index if not exists lead_radar_seen_source_id_uidx
  on public.lead_radar_seen_items(source, source_id)
  where source_id is not null;

create index if not exists lead_radar_seen_last_seen_idx
  on public.lead_radar_seen_items(last_seen_at desc);

alter table public.lead_radar_seen_items enable row level security;
revoke all on table public.lead_radar_seen_items from anon, authenticated;
revoke all on sequence public.lead_radar_seen_items_id_seq from anon, authenticated;

comment on table public.lead_radar_seen_items is
  'Server-only dedupe ledger for every source candidate, including filtered non-leads, so repeated source results do not repeatedly consume AI classification cost.';
