create table if not exists public.lead_radar_retrieval_settings (
  id smallint primary key default 1 check (id = 1),
  auto_enabled boolean not null default false,
  auto_interval_minutes integer not null default 60 check (auto_interval_minutes between 15 and 1440),
  auto_queries_per_scan integer not null default 1 check (auto_queries_per_scan between 1 and 3),
  auto_provider_calls_per_scan integer not null default 1 check (auto_provider_calls_per_scan between 1 and 6),
  manual_queries_per_scan integer not null default 2 check (manual_queries_per_scan between 1 and 3),
  manual_provider_calls_per_scan integer not null default 3 check (manual_provider_calls_per_scan between 1 and 6),
  provider_calls_per_hour_cap integer not null default 6 check (provider_calls_per_hour_cap between 1 and 30),
  updated_at timestamptz not null default now()
);

insert into public.lead_radar_retrieval_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.lead_radar_retrieval_settings enable row level security;

create table if not exists public.lead_radar_query_runs (
  id bigint generated by default as identity primary key,
  scan_request_id bigint references public.lead_radar_scan_requests(id) on delete set null,
  provider text not null default 'justone-xiaohongshu-v4',
  retrieval_version text not null,
  query_key text not null,
  query_text text not null,
  lane text not null,
  intent_family text not null,
  topic_family text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz not null default now(),
  pages integer not null default 1 check (pages >= 0),
  api_calls integer not null default 1 check (api_calls >= 0),
  returned_count integer not null default 0 check (returned_count >= 0),
  normalized_count integer not null default 0 check (normalized_count >= 0),
  fresh_count integer not null default 0 check (fresh_count >= 0),
  qualified_count integer not null default 0 check (qualified_count >= 0),
  filtered_count integer not null default 0 check (filtered_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  newest_published_at timestamptz,
  oldest_published_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists lead_radar_query_runs_key_started_idx
  on public.lead_radar_query_runs (query_key, started_at desc);
create index if not exists lead_radar_query_runs_started_idx
  on public.lead_radar_query_runs (started_at desc);
create index if not exists lead_radar_query_runs_scan_request_idx
  on public.lead_radar_query_runs (scan_request_id);

alter table public.lead_radar_query_runs enable row level security;

create table if not exists public.lead_radar_query_observations (
  id bigint generated by default as identity primary key,
  query_run_id bigint not null references public.lead_radar_query_runs(id) on delete cascade,
  source text not null,
  source_id text not null,
  lead_id bigint references public.lead_radar_leads(id) on delete set null,
  disposition text not null,
  score integer,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (query_run_id, source, source_id)
);

create index if not exists lead_radar_query_observations_source_idx
  on public.lead_radar_query_observations (source, source_id);
create index if not exists lead_radar_query_observations_lead_idx
  on public.lead_radar_query_observations (lead_id);

alter table public.lead_radar_query_observations enable row level security;

create or replace view public.lead_radar_query_scheduler_stats as
with run_stats as (
  select
    r.query_key,
    max(r.query_text) as query_text,
    max(r.lane) as lane,
    max(r.intent_family) as intent_family,
    max(r.topic_family) as topic_family,
    count(*)::integer as runs,
    coalesce(sum(r.api_calls), 0)::integer as api_calls,
    coalesce(sum(r.returned_count), 0)::integer as returned_count,
    coalesce(sum(r.fresh_count), 0)::integer as fresh_count,
    coalesce(sum(r.qualified_count), 0)::integer as qualified_count,
    coalesce(sum(r.filtered_count), 0)::integer as filtered_count,
    coalesce(sum(r.duplicate_count), 0)::integer as duplicate_count,
    max(r.started_at) as last_run_at
  from public.lead_radar_query_runs r
  where r.started_at >= now() - interval '14 days'
  group by r.query_key
), latest_feedback as (
  select distinct on (f.source, f.source_id)
    f.source, f.source_id, f.label
  from public.lead_radar_feedback f
  order by f.source, f.source_id, f.updated_at desc, f.id desc
), observed_items as (
  select distinct
    r.query_key,
    o.source,
    o.source_id,
    f.label
  from public.lead_radar_query_runs r
  join public.lead_radar_query_observations o on o.query_run_id = r.id
  left join latest_feedback f on f.source = o.source and f.source_id = o.source_id
  where r.started_at >= now() - interval '14 days'
), feedback_stats as (
  select
    query_key,
    count(*) filter (where label in ('lead', 'true_lead'))::integer as human_positive_count,
    count(*) filter (where label in ('not_lead', 'false_lead'))::integer as human_negative_count
  from observed_items
  group by query_key
)
select
  r.query_key,
  r.query_text,
  r.lane,
  r.intent_family,
  r.topic_family,
  r.runs,
  r.api_calls,
  r.returned_count,
  r.fresh_count,
  r.qualified_count,
  r.filtered_count,
  r.duplicate_count,
  coalesce(f.human_positive_count, 0) as human_positive_count,
  coalesce(f.human_negative_count, 0) as human_negative_count,
  r.last_run_at
from run_stats r
left join feedback_stats f using (query_key);

create or replace function public.lead_radar_claim_scan_work(p_run_id text, p_allow_auto boolean default false)
returns table(
  id bigint,
  query_override text,
  max_queries integer,
  requested_at timestamptz,
  requested_from text,
  provider_call_budget integer
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_claimed integer := 0;
  v_calls_last_hour integer := 0;
  v_remaining integer := 0;
  v_cap integer := 0;
  v_auto_enabled boolean := false;
  v_auto_interval integer := 60;
  v_auto_queries integer := 1;
  v_auto_budget integer := 1;
  v_manual_budget integer := 3;
begin
  update public.lead_radar_scan_requests r
  set status = 'failed',
      finished_at = now(),
      updated_at = now(),
      error_text = 'Collector timeout recovery',
      result = jsonb_build_object('recovered', true, 'reason', 'running_timeout')
  where r.status = 'running'
    and r.started_at is not null
    and r.started_at < now() - interval '20 minutes';

  select
    s.auto_enabled,
    s.auto_interval_minutes,
    s.auto_queries_per_scan,
    s.auto_provider_calls_per_scan,
    s.manual_provider_calls_per_scan,
    s.provider_calls_per_hour_cap
  into
    v_auto_enabled,
    v_auto_interval,
    v_auto_queries,
    v_auto_budget,
    v_manual_budget,
    v_cap
  from public.lead_radar_retrieval_settings s
  where s.id = 1;

  select coalesce(sum(q.api_calls), 0)::integer
  into v_calls_last_hour
  from public.lead_radar_query_runs q
  where q.started_at >= now() - interval '1 hour';

  v_remaining := greatest(v_cap - v_calls_last_hour, 0);
  if v_remaining <= 0 then
    return;
  end if;

  return query
  with candidate as (
    select r.id
    from public.lead_radar_scan_requests r
    where r.status = 'queued'
    order by r.requested_at asc
    for update skip locked
    limit 1
  ), claimed as (
    update public.lead_radar_scan_requests r
    set status = 'running',
        started_at = now(),
        updated_at = now(),
        github_run_id = nullif(left(coalesce(p_run_id, ''), 120), '')
    from candidate c
    where r.id = c.id
    returning r.id, r.query_override, r.max_queries, r.requested_at, r.requested_from
  )
  select
    c.id,
    c.query_override,
    c.max_queries,
    c.requested_at,
    c.requested_from,
    least(
      v_remaining,
      case when c.requested_from = 'auto' then v_auto_budget else v_manual_budget end
    )::integer
  from claimed c;

  get diagnostics v_claimed = row_count;
  if v_claimed > 0 or not coalesce(p_allow_auto, false) or not coalesce(v_auto_enabled, false) then
    return;
  end if;

  if exists (
    select 1
    from public.lead_radar_scan_requests r
    where r.requested_from = 'auto'
      and r.requested_at >= now() - make_interval(mins => greatest(v_auto_interval, 15))
  ) then
    return;
  end if;

  return query
  with created as (
    insert into public.lead_radar_scan_requests (
      requested_from,
      max_queries,
      provider,
      status,
      started_at,
      updated_at,
      github_run_id
    ) values (
      'auto',
      greatest(1, least(3, v_auto_queries)),
      'justone-xiaohongshu-v4',
      'running',
      now(),
      now(),
      nullif(left(coalesce(p_run_id, ''), 120), '')
    )
    returning lead_radar_scan_requests.id,
              lead_radar_scan_requests.query_override,
              lead_radar_scan_requests.max_queries,
              lead_radar_scan_requests.requested_at,
              lead_radar_scan_requests.requested_from
  )
  select
    c.id,
    c.query_override,
    c.max_queries,
    c.requested_at,
    c.requested_from,
    least(v_remaining, v_auto_budget)::integer
  from created c;
end;
$function$;
